### ISSUE TITLE
Multiworld item checks don't show message (item / receiver) in in-game console

### ISSUE THREAD

**Issue by adampziegler** [Ijwu/Archipelago.RiskOfRain2#7] opened 2022-02-04 05:24 UTC
AP version: 0.2.3, 0.2.4
RoR2 AP mod version: 1.0.2 (all mod dependencies at latest versions as of 03 Feb)

When triggering an item check that would send an item to another player, no message is shown in the source player's RoR 2 in-game chat/console detailing what that item is or which player received it.  Opening the chat/console in-game shows messages from the server and other players/clients (but not the server's item-send message for the sender's RoR 2 game).  The destination player does receive the item as expected.

![image](https://user-images.githubusercontent.com/6360335/152476629-8d45c700-fb8c-441f-a841-b82c16372815.png)

I believe the message was shown as recently as AP 0.2.2 / mod version 1.0.1, but I am not certain.

**Comment by Ijwu** [comment] 2022-02-04 22:25
Thanks for submitting this, this is a known issue that I've been meaning to release a minor release for in order to fix. I've just been awful about it. Hopefully this weekend will see it come out.

**Comment by Ijwu** [comment] 2022-07-29 12:51
I believe this is fixed in a recent release. Thanks again. Reopen this if the issue is still present.

**Closed as completed by Ijwu** 2022-07-29 12:51 UTC
Labels: bug

**Comment by adampziegler** [comment] 2022-08-11 04:55
v1.1.1 shows item send messages as expected; thanks for the fix!
